containers:
  core: # name of the docker container
    image: skiffos/skiff-core-fedora:latest
    entrypoint: ["/lib/systemd/systemd"]
    # systemd: indicate this is a container
    env: ["container=docker"]
    stopSignal: RTMIN+3
    tty: true
    disableInit: true
    workingDirectory: /
    # default DNS servers
    dns: ["1.1.1.1", "8.8.8.8"]
    mounts:
      - /dev:/dev
      - /etc/hostname:/etc/hostname:ro
      - /lib/modules:/lib/modules:ro
      - /mnt:/mnt
      - /run/udev:/run/udev
      - /mnt/persist/skiff/core/repos/dnf:/var/lib/dnf/repos
      - /mnt/persist/skiff/core/repos/snapd:/var/lib/snapd
      - /mnt/persist/skiff/core/repos/flatpak:/var/lib/flatpak
      - /mnt/persist/skiff/core/repos/linux:/usr/src
      - /mnt/persist/skiff/core/repos/log:/var/log
      - /mnt/persist/skiff/core/repos/tmp:/var/tmp
    privileged: true
    startAfterCreate: true
    restartPolicy: "always"
    capAdd:
    - ALL
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    securityOpt:
    - seccomp=unconfined
    tmpFs:
      /run: rw,noexec,nosuid,size=65536k
      /run/lock: rw,noexec,nosuid,size=65536k
users: # can add unlimited users
  core:
    container: core
    containerUser: core
    containerShell:
    - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  skiffos/skiff-core-fedora:latest:
    pull:
      policy: ifnotexists
      registry: quay.io
    build:
      source: /opt/skiff/coreenv/skiff-core-fedora
